<a href="https://colab.research.google.com/github/arutraj/.githubcl/blob/main/7_4_Levenshtein_distance_to_calculate_string_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
# importing library
import numpy as np

In [21]:
# defining two strings
seq1 = 'text'
seq2 = 'test'

![](https://drive.google.com/uc?export=view&id=1ev-00rhE1Waiy9VbdR2KpO_ML4JnosWj)

In [22]:
# size of matrix
size_x = len(seq1) + 1
size_y = len(seq2) + 1
# creating a matrix with all zeros
matrix = np.zeros((size_x, size_y))

# printing the matrix
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# filling the first column of the matrix with the index of characters from first string
for x in range(size_x):
    matrix [x, 0] = x
# filling the first row of the matrix with the index of characters from second string
for y in range(size_y):
    matrix [0, y] = y

# printing the matrix
matrix

array([[0., 1., 2., 3., 4.],
       [1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.]])

In [24]:
# for each column
for x in range(1, size_x):
    # for each row
    for y in range(1, size_y):
        # check if the characters are same
        if seq1[x-1] == seq2[y-1]:
            # fill the element with the minimum of (diagonal value, first corresponding value + 1, second corresponding value + 1)
            matrix [x,y] = min(
                matrix[x-1, y-1],
                matrix[x-1, y] + 1,
                matrix[x, y-1] + 1
            )
        # if characters are not same
        else:
            # fill the element with the minimum of corresponding values + 1
            matrix [x,y] = min(
                matrix[x-1,y] + 1,
                matrix[x-1,y-1] + 1,
                matrix[x,y-1] + 1
            )

# final matrix
matrix

array([[0., 1., 2., 3., 4.],
       [1., 0., 1., 2., 3.],
       [2., 1., 0., 1., 2.],
       [3., 2., 1., 1., 2.],
       [4., 3., 2., 2., 1.]])

In [25]:
# levenshtein distance
matrix[size_x - 1, size_y - 1]

1.0

In [26]:
# defining the function to calculate levenshtein distance between two strings
def levenshtein_distance(seq1, seq2):

    # size of matrix
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    # creating a matrix with all zeros
    matrix = np.zeros((size_x, size_y))

    # filling the first column of the matrix with the index of characters from first string
    for x in range(size_x):
        matrix [x, 0] = x
    # filling the first row of the matrix with the index of characters from second string
    for y in range(size_y):
        matrix [0, y] = y

    # for each column
    for x in range(1, size_x):
        # for each row
        for y in range(1, size_y):
            # check if the characters are same
            if seq1[x-1] == seq2[y-1]:
                # fill the element with the minimum of (diagonal value, first corresponding value + 1, second corresponding value + 1)
                matrix [x,y] = min(
                    matrix[x-1, y-1],
                    matrix[x-1, y] + 1,
                    matrix[x, y-1] + 1
                )
            # if characters are not same
            else:
                # fill the element with the minimum of corresponding values + 1
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )

    # printing the final matrix
    print (matrix)

    # returning the levenshtein distance
    return (matrix[size_x - 1, size_y - 1])

In [27]:
# defining two sequences
seq1 = 'scientist'
seq2 = 'science'

In [28]:
levenshtein_distance(seq1, seq2)

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [1. 0. 1. 2. 3. 4. 5. 6.]
 [2. 1. 0. 1. 2. 3. 4. 5.]
 [3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 3. 2. 1. 0. 1. 2. 3.]
 [5. 4. 3. 2. 1. 0. 1. 2.]
 [6. 5. 4. 3. 2. 1. 1. 2.]
 [7. 6. 5. 4. 3. 2. 2. 2.]
 [8. 7. 6. 5. 4. 3. 3. 3.]
 [9. 8. 7. 6. 5. 4. 4. 4.]]


4.0

In [29]:
# defining two sequences
seq1 = 'learning'
seq2 = 'learnt'

In [30]:
levenshtein_distance(seq1, seq2)

[[0. 1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 2. 3. 4. 5.]
 [2. 1. 0. 1. 2. 3. 4.]
 [3. 2. 1. 0. 1. 2. 3.]
 [4. 3. 2. 1. 0. 1. 2.]
 [5. 4. 3. 2. 1. 0. 1.]
 [6. 5. 4. 3. 2. 1. 1.]
 [7. 6. 5. 4. 3. 2. 2.]
 [8. 7. 6. 5. 4. 3. 3.]]


3.0